### ISSUE TITLE
老师，我真找不到你了，我现在遇到了点问题

### ISSUE THREAD

**Issue by wangjunbo993** [itstrive/striveCode#5]
webpack-simple打包的时候文件不全，网上资料也特别少，
我run build打包出来的只有：build.js和build.js.map，和几张图片，问题出在哪呢？我是按照你的步骤来的

**Comment by itstrive** [comment]
打包上线时，建议你用 webpack 这个模板。
现在开发时，我也建议用webpack这个，你可以把代码检查关闭了，或者自己配置下。
当时上课只是为了省事了 @wangjunbo993
